name: "30 Timeframe"
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  update-data:
    name: Thirty Timeframe
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Apt-get needed things
        run: |
          sudo apt-get update -y && 
          sudo apt-get upgrade -y &&
          sudo apt-get dist-upgrade -y &&
          sudo apt-get clean all && 
          sudo apt-get install --no-install-recommends -y \
          apt-utils && 
          sudo apt-get install --no-install-recommends -y \
          r-base-core \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: "Install Packages"
        run: |
          install.packages('tidyverse')
          install.packages('httr')
          install.packages('jsonlite')
          install.packages('janitor')
        shell: Rscript {0}
      - name: "Script - Run"
        run: Rscript 'get_audiences.R'
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Script Routine Thirty
